# Generated by Django 4.0.5 on 2022-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_token',
            name='access_token',
            field=models.TextField(),
        ),
    ]
