# Generated by Django 4.0.5 on 2022-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_playlists_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='id_spotify',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
