# Generated by Django 4.0.5 on 2022-07-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlists_id_spotify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='name',
            new_name='badge_type',
        ),
        migrations.AddField(
            model_name='badge',
            name='playlist',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='music.playlists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User_Badge',
        ),
    ]
