# Generated by Django 4.0.5 on 2022-07-23 11:00

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_events_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
