# Generated by Django 4.0.5 on 2022-07-23 10:48

from django.db import migrations, models

from ..models import Events


def add_events(apps, schema_editor):
    new_1 = Events.objects.create(
        name="Şehinşah",
        location="Mask Beach",
        link="https://www.biletix.com/etkinlik/1MY12/TURKIYE/tr",
        city_id=34,
        photo="https://www.biletix.com/static/images/live/event/eventimages/0DN19-gorsel.png",
    )
    new_1.save()
    new_2 = Events.objects.create(
        name="Sertap Erener",
        location="Harbiye Cemil Topuzlu Açık Hava Tiyatrosu",
        link="https://www.biletix.com/etkinlik/15A95/TURKIYE/tr",
        city_id=34,
        photo="https://www.biletix.com/static/images/live/event/eventimages/15A95_sartabbkm.jpg",
    )
    new_2.save()
    new_3 = Events.objects.create(
        name="Melike Şahin",
        location = "Maximum Uniq Açıkhava",
        link="https://www.biletix.com/etkinlik/15A03/TURKIYE/tr",
        city_id=34,
        photo="https://www.biletix.com/static/images/live/event/eventimages/15A03_melikesahin.jpg",
    )
    new_3.save()
    new_4 = Events.objects.create(
        name="Evdeki Saat",
        location = "6.45 KK",
        link="https://www.biletix.com/etkinlik/1MO69/TURKIYE/tr",
        city_id=6,
        photo="https://www.biletix.com/static/images/live/event/eventimages/evdekisaat0JJ28.png",
    )
    new_4.save()
    new_5 = Events.objects.create(
        name="Bülent Ortaçgil",
        location ="ODTÜ Vişnelik",
        link="https://www.biletix.com/etkinlik-grup/323120400/TURKIYE/tr",
        city_id=6,
        photo="https://www.biletix.com/static/images/live/event/groupimages/bulentgroup.png",
    )
    new_5.save()
    new_6 = Events.objects.create(
        name="Mor ve Ötesi",
        location = "Atılım Üniversitesi Amfi Tiyatro",
        link="https://www.biletix.com/etkinlik/1LA19/TURKIYE/tr",
        city_id=6,
        photo="https://www.biletix.com/static/images/live/event/eventimages/1l724yeni.jpg",
    )
    new_6.save()


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_events_location"),
    ]

    operations = [migrations.RunPython(add_events)]
