# Generated by Django 4.0.5 on 2022-07-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_add_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='photo',
            field=models.TextField(),
        ),
    ]
